Fix E2E: set --allow-system-access (#1607)
geckodriver 0.37.1 requires the --allow-system-access argument now to navigate to moz-extension:// URLs. Or maybe it requires it for navigation in general. Either way, without this change, e2e tests fail with:

    UnsupportedOperationError: Navigation to "moz-extension://595108c3-fc1a-46bc-a6f6-918a6b1898aa/site/index.html" is not allowed in this context