Don't remove cookie on auth selection
Don't remove a manually entered Cookie header when selecting an
authorization in the Authorization tab. This works by flagging headers
added through the Authorization tab. Only flagged headers are removed
when selecting another authorization.

Exception: if the selected authorization adds an "Authorization" header,
it will override any existing "Authorization" header. And if the
selected authorization adds a "Cookie" header, it will override any
existing "Cookie" header.